//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateEnterySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ENTRY
    {
        public int ENTRYNUMBER { get; set; }
        public string CNIC { get; set; }
        public string FULLNAME { get; set; }
        public string CONTACTNUMBER { get; set; }
        public string ENTRYREASON { get; set; }
        public string ENTRYDATEANDTIME { get; set; }
        public string ENTRYINOUT { get; set; }
        public string ENTRYTIME { get; set; }
    }
}
